### ISSUE TITLE
Getting an error on payment which fits channel capacity totally

### ISSUE THREAD

**Issue by tonymorony** [Mixa84/To-Do#12]
Seems I've faced bug in ChannelsCC.

**Calls to reproduce:** https://paste.ubuntu.com/p/hc7zQxtp8w/ 

**Description:** 
When sending payment which covers channel capacity fully throwing an error: 
```
CC Eval EVAL_CHANNELS Invalid: vout.0 is CC for channelPayment! spending tx 1c05abb9e5c892c8bd2e8dee9f35f27e6ddc7fc4d61e6f94b455a0c84ac75247
error code: -26
error message:
16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)
```

So let's say if open a channel of 10 payments max with 100000 sat denomination you'll able to send 9 payments of 100000 sat but will get an error on 10th 100000 sat payment

Or open a channel of 10 payments max with 100000 sat denomination send 100000 sat payment, 800000 sat payment and get an error when sending last 100000 and so on

**Comment by Mixa84** [comment]
Fixed.
https://github.com/jl777/komodo/commit/478a31f4635618e30075fd5672c2296608639e34
