### ISSUE TITLE
Ability to cancel other people's token asks/bids

### ISSUE THREAD

**Issue by Alrighttt** [Mixa84/To-Do#15]
It's possible to use both `tokencancelbid` and `tokencancelask` on other people's orders simply by setting the pubkey used to create the bid/ask with `pubkey=` at startup.

**Comment by Mixa84** [comment]
Fixed!
It will be available in new asset and tokens split on dimxy GitHub until it is merged in FSM - https://github.com/dimxy/komodo/pull/1
